services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nimonspedia-app
    volumes:
      - ./php/src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    networks:
      - nimonspedia-net

  db:
    image: postgres:15-alpine
    container_name: nimonspedia-db
    environment:
      POSTGRES_DB: nimonspedia_db
      POSTGRES_USER: nimonspedia_user
      POSTGRES_PASSWORD: nimonspedia_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nimonspedia-net

  nginx:
    image: nginx:alpine
    container_name: nimonspedia-nginx
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - nimonspedia-net

volumes:
  db_data:

networks:
  nimonspedia-net:
    driver: bridge